name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    environment: production

    runs-on: ubuntu-latest
    env:
      SCALEWAY_CONTAINER_URL: ${{ secrets.SCALEWAY_CONTAINER_URL }}
      SCALEWAY_CONTAINER_ID: ${{ secrets.SCALEWAY_CONTAINER_ID }}
      CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}

    steps:
    - uses: actions/checkout@v4
    - name: Copy config file templates
      run: |
        cp config/config.example.json config/config.json
        cp config/debug.example.json config/debug.json
        echo '[]' > config/bot-sites.json
    - name: Setup config files
      run: |
        sed -i "s|<YOUR_DISCORD_ID>|${{ secrets.DISCORD_DEVELOPER_ID }}|g" config/config.json
        sed -i "s|<DISCORD_BOT_ID>|${{ secrets.DISCORD_BOT_ID }}|g" config/config.json
        sed -i "s|<DISCORD_BOT_TOKEN>|${{ secrets.DISCORD_BOT_TOKEN }}|g" config/config.json
        sed -i 's|"00000000-0000-0000-0000-000000000000"|"${{ secrets.API_SECRET }}"|g' config/config.json
        sed -i 's|"<DISCORD_NOTIFICATION_CHANNEL_ID>"|${{ vars.DISCORD_NOTIFICATION_CHANNEL_ID }}|g' config/config.json
    - name: Docker login
      run: docker login "${{ env.SCALEWAY_CONTAINER_URL }}/${{ env.SCALEWAY_CONTAINER_ID }}" -u nologin --password-stdin <<< "${{ secrets.SCALEWAY_TOKEN }}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ env.SCALEWAY_CONTAINER_URL }}/${{ env.SCALEWAY_CONTAINER_ID }}/${{ env.CONTAINER_NAME }}:latest" --platform=linux/amd64
    - name: Push to Container Registry
      run: docker push "${{ env.SCALEWAY_CONTAINER_URL }}/${{ env.SCALEWAY_CONTAINER_ID }}/${{ env.CONTAINER_NAME }}:latest"
