name: Upload OpenAPI Specification

on:
  push:
    branches:
      - main
    paths:
      - 'swagger/**'

jobs:
  upload-openapi-spec:
    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload OpenAPI spec
        uses: hey-api/upload-openapi-spec@v1.3.0
        with:
          path-to-file: swagger/v1/swagger.json
        env:
          API_KEY: ${{ secrets.HEY_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
